/* 첨부파일_시퀀스 */
CREATE SEQUENCE seq_box 
	INCREMENT BY 1
	START WITH 1;

/* 포스트_시퀀스 */
CREATE SEQUENCE seq_post;

/* 검석어_시퀀스 */
CREATE SEQUENCE seq_search;

/* 댓글_시퀀스 */
CREATE SEQUENCE seq_comment;

/* 카테고리_시퀀스 */
CREATE SEQUENCE seq_category;

/* 메세지_시퀀스 */
CREATE SEQUENCE seq_message;

/* 회원 */
CREATE TABLE USER_H (
	ID VARCHAR2(50) NOT NULL, /* ID */
	PASSWORD VARCHAR2(50) NOT NULL, /* 비밀번호 */
	BIRTH DATE NOT NULL, /* 생년월일 */
	SEX VARCHAR2(10) NOT NULL, /* 성별 */
	NAME VARCHAR2(50) NOT NULL, /* 닉네임 */
	EMAIL VARCHAR2(200) NOT NULL, /* EMAIL */
	AREA VARCHAR2(50), /* 지역 */
	GRADE VARCHAR2(50) NOT NULL, /* 등급 */
	PF_IMAGE VARCHAR2(500), /* 프로필사진주소 */
	PF_CONTENT VARCHAR2(500) /* 프로필내용 */
);

COMMENT ON TABLE USER_H IS '회원';

COMMENT ON COLUMN USER_H.ID IS 'ID';

COMMENT ON COLUMN USER_H.PASSWORD IS '비밀번호';

COMMENT ON COLUMN USER_H.BIRTH IS '생년월일';

COMMENT ON COLUMN USER_H.SEX IS '성별';

COMMENT ON COLUMN USER_H.NAME IS '닉네임';

COMMENT ON COLUMN USER_H.EMAIL IS 'EMAIL';

COMMENT ON COLUMN USER_H.AREA IS '지역';

COMMENT ON COLUMN USER_H.GRADE IS '등급';

COMMENT ON COLUMN USER_H.PF_IMAGE IS '프로필사진주소';

COMMENT ON COLUMN USER_H.PF_CONTENT IS '프로필내용';

CREATE UNIQUE INDEX PK_USER_H
	ON USER_H (
		ID ASC
	);

CREATE UNIQUE INDEX UIX_USER_H
	ON USER_H (
		NAME ASC,
		EMAIL ASC
	);

ALTER TABLE USER_H
	ADD
		CONSTRAINT PK_USER_H
		PRIMARY KEY (
			ID
		);

ALTER TABLE USER_H
	ADD
		CONSTRAINT UK_USER_H
		UNIQUE (
			NAME,
			EMAIL
		);

/* 블로그 */
CREATE TABLE BLOG_H (
	ID VARCHAR2(50) NOT NULL, /* ID */
	TITLE VARCHAR2(200) NOT NULL, /* 제목 */
	THEME VARCHAR2(200) DEFAULT 'DEFAULT_THEME' NOT NULL /* 테마 */
);

COMMENT ON TABLE BLOG_H IS '블로그';

COMMENT ON COLUMN BLOG_H.ID IS 'ID';

COMMENT ON COLUMN BLOG_H.TITLE IS '제목';

COMMENT ON COLUMN BLOG_H.THEME IS '테마';

CREATE UNIQUE INDEX PK_BLOG_H
	ON BLOG_H (
		ID ASC
	);

ALTER TABLE BLOG_H
	ADD
		CONSTRAINT PK_BLOG_H
		PRIMARY KEY (
			ID
		);

/* 포스트 */
CREATE TABLE POST_H (
	SEQ NUMBER NOT NULL, /* 시퀀스 */
	CT_SEQ NUMBER NOT NULL, /* 카테고리ID */
	ID VARCHAR2(50) NOT NULL, /* ID */
	FIELD VARCHAR2(100), /* 글주제 */
	TITLE VARCHAR2(200) NOT NULL, /* 글제목 */
	CONTENT CLOB NOT NULL, /* 글내용 */
	WDATE DATE DEFAULT SYSDATE NOT NULL, /* 작성일 */
	HASHTAG VARCHAR2(2000), /* 해시태그 */
	STATE VARCHAR2(1) DEFAULT 0 NOT NULL /* 상태 */
);

COMMENT ON TABLE POST_H IS '포스트';

COMMENT ON COLUMN POST_H.SEQ IS '시퀀스';

COMMENT ON COLUMN POST_H.CT_SEQ IS '카테고리ID';

COMMENT ON COLUMN POST_H.ID IS 'ID';

COMMENT ON COLUMN POST_H.FIELD IS '글주제';

COMMENT ON COLUMN POST_H.TITLE IS '글제목';

COMMENT ON COLUMN POST_H.CONTENT IS '글내용';

COMMENT ON COLUMN POST_H.WDATE IS '작성일';

COMMENT ON COLUMN POST_H.HASHTAG IS '해시태그';

COMMENT ON COLUMN POST_H.STATE IS '상태';

CREATE UNIQUE INDEX PK_POST_H
	ON POST_H (
		SEQ ASC
	);

ALTER TABLE POST_H
	ADD
		CONSTRAINT PK_POST_H
		PRIMARY KEY (
			SEQ
		);

/* 카테고리 */
CREATE TABLE CATEGORY_H (
	SEQ NUMBER NOT NULL, /* 시퀀스 */
	ID VARCHAR2(50) NOT NULL, /* ID */
	NAME VARCHAR2(200) NOT NULL, /* 카테고리명 */
	STATE VARCHAR2(1) DEFAULT 0 NOT NULL /* 상태 */
);

COMMENT ON TABLE CATEGORY_H IS '카테고리';

COMMENT ON COLUMN CATEGORY_H.SEQ IS '시퀀스';

COMMENT ON COLUMN CATEGORY_H.ID IS 'ID';

COMMENT ON COLUMN CATEGORY_H.NAME IS '카테고리명';

COMMENT ON COLUMN CATEGORY_H.STATE IS '상태';

CREATE UNIQUE INDEX PK_CATEGORY_H
	ON CATEGORY_H (
		SEQ ASC
	);

ALTER TABLE CATEGORY_H
	ADD
		CONSTRAINT PK_CATEGORY_H
		PRIMARY KEY (
			SEQ
		);

/* 첨부파일 */
CREATE TABLE BOX_H (
	SEQ NUMBER NOT NULL, /* 시퀀스 */
	POST_SEQ NUMBER NOT NULL, /* 포스트ID */
	LOCATION VARCHAR2(1) NOT NULL, /* 첨부파일여부 */
	ORI_NAME VARCHAR2(200) NOT NULL, /* 원본이름 */
	SAVE_NAME VARCHAR2(200) NOT NULL /* 저장이름 */
);

COMMENT ON TABLE BOX_H IS '첨부파일';

COMMENT ON COLUMN BOX_H.SEQ IS '시퀀스';

COMMENT ON COLUMN BOX_H.POST_SEQ IS '포스트ID';

COMMENT ON COLUMN BOX_H.LOCATION IS '첨부파일여부';

COMMENT ON COLUMN BOX_H.ORI_NAME IS '원본이름';

COMMENT ON COLUMN BOX_H.SAVE_NAME IS '저장이름';

CREATE UNIQUE INDEX PK_BOX_H
	ON BOX_H (
		SEQ ASC
	);

ALTER TABLE BOX_H
	ADD
		CONSTRAINT PK_BOX_H
		PRIMARY KEY (
			SEQ
		);

/* 게시판댓글 */
CREATE TABLE COMMENT_H (
	SEQ NUMBER NOT NULL, /* 시퀀스 */
	POST_SEQ NUMBER NOT NULL, /* 포스트ID */
	ID VARCHAR2(50) NOT NULL, /* ID */
	NAME VARCHAR2(50) NOT NULL, /* 닉네임 */
	CONTENT VARCHAR2(600) NOT NULL, /* 내용 */
	PARENT NUMBER NOT NULL, /* 부모 */
	STATE VARCHAR2(1) DEFAULT 0 NOT NULL, /* 상태 */
	WDATE DATE DEFAULT SYSDATE NOT NULL /* 작성일 */
);

COMMENT ON TABLE COMMENT_H IS '게시판댓글';

COMMENT ON COLUMN COMMENT_H.SEQ IS '시퀀스';

COMMENT ON COLUMN COMMENT_H.POST_SEQ IS '포스트ID';

COMMENT ON COLUMN COMMENT_H.ID IS 'ID';

COMMENT ON COLUMN COMMENT_H.NAME IS '닉네임';

COMMENT ON COLUMN COMMENT_H.CONTENT IS '내용';

COMMENT ON COLUMN COMMENT_H.PARENT IS '부모';

COMMENT ON COLUMN COMMENT_H.STATE IS '상태';

COMMENT ON COLUMN COMMENT_H.WDATE IS '작성일';

CREATE UNIQUE INDEX PK_COMMENT_H
	ON COMMENT_H (
		SEQ ASC
	);

ALTER TABLE COMMENT_H
	ADD
		CONSTRAINT PK_COMMENT_H
		PRIMARY KEY (
			SEQ
		);

/* 메세지 */
CREATE TABLE MESSAGE_H (
	SEQ NUMBER NOT NULL, /* 시퀀스 */
	SEND_ID VARCHAR2(50) NOT NULL, /* 송신자 */
	TAKE_ID VARCHAR2(50) NOT NULL, /* 수신자 */
	WDATE DATE DEFAULT SYSDATE NOT NULL, /* 작성일 */
	RDATE DATE, /* 확인일 */
	STATE VARCHAR2(1) DEFAULT 0 NOT NULL /* 상태 */
);

COMMENT ON TABLE MESSAGE_H IS '메세지';

COMMENT ON COLUMN MESSAGE_H.SEQ IS '시퀀스';

COMMENT ON COLUMN MESSAGE_H.SEND_ID IS '송신자';

COMMENT ON COLUMN MESSAGE_H.TAKE_ID IS '수신자';

COMMENT ON COLUMN MESSAGE_H.WDATE IS '작성일';

COMMENT ON COLUMN MESSAGE_H.RDATE IS '확인일';

COMMENT ON COLUMN MESSAGE_H.STATE IS '상태';

CREATE UNIQUE INDEX PK_MESSAGE_H
	ON MESSAGE_H (
		SEQ ASC
	);

ALTER TABLE MESSAGE_H
	ADD
		CONSTRAINT PK_MESSAGE_H
		PRIMARY KEY (
			SEQ
		);

/* 글 공감 */
CREATE TABLE LOVE_H (
	POST_SEQ NUMBER NOT NULL, /* 포스트ID */
	ID VARCHAR2(50) NOT NULL, /* ID */
	LDATE DATE DEFAULT SYSDATE NOT NULL, /* 날짜 */
	SEX VARCHAR2(10) NOT NULL, /* 성별 */
	AREA VARCHAR2(50), /* 지역 */
	BIRTH DATE NOT NULL /* 생년월일 */
);

COMMENT ON TABLE LOVE_H IS '글 공감';

COMMENT ON COLUMN LOVE_H.POST_SEQ IS '포스트ID';

COMMENT ON COLUMN LOVE_H.ID IS 'ID';

COMMENT ON COLUMN LOVE_H.LDATE IS '날짜';

COMMENT ON COLUMN LOVE_H.SEX IS '성별';

COMMENT ON COLUMN LOVE_H.AREA IS '지역';

COMMENT ON COLUMN LOVE_H.BIRTH IS '생년월일';

CREATE UNIQUE INDEX PK_LOVE_H
	ON LOVE_H (
		POST_SEQ ASC,
		ID ASC
	);

ALTER TABLE LOVE_H
	ADD
		CONSTRAINT PK_LOVE_H
		PRIMARY KEY (
			POST_SEQ,
			ID
		);

/* 팔로우 */
CREATE TABLE FOLLOW_H (
	MY_ID VARCHAR2(50) NOT NULL, /* 내ID */
	YOU_ID VARCHAR2(50) NOT NULL, /* 너ID */
	FDATE DATE DEFAULT SYSDATE NOT NULL, /* 날짜 */
	SEX VARCHAR2(10) NOT NULL, /* 성별 */
	AREA VARCHAR2(50), /* 지역 */
	BIRTH DATE NOT NULL /* 생년월일 */
);

COMMENT ON TABLE FOLLOW_H IS '팔로우';

COMMENT ON COLUMN FOLLOW_H.MY_ID IS '내ID';

COMMENT ON COLUMN FOLLOW_H.YOU_ID IS '너ID';

COMMENT ON COLUMN FOLLOW_H.FDATE IS '날짜';

COMMENT ON COLUMN FOLLOW_H.SEX IS '성별';

COMMENT ON COLUMN FOLLOW_H.AREA IS '지역';

COMMENT ON COLUMN FOLLOW_H.BIRTH IS '생년월일';

CREATE UNIQUE INDEX PK_FOLLOW_H
	ON FOLLOW_H (
		MY_ID ASC,
		YOU_ID ASC
	);

ALTER TABLE FOLLOW_H
	ADD
		CONSTRAINT PK_FOLLOW_H
		PRIMARY KEY (
			MY_ID,
			YOU_ID
		);

/* 방문자 */
CREATE TABLE VISIT_H (
	ID VARCHAR2(50) NOT NULL, /* 접속한BLOG_ID */
	V_ID VARCHAR2(50), /* 방문자 ID */
	VDATE DATE DEFAULT SYSDATE NOT NULL, /* 날짜 */
	SEX VARCHAR2(10), /* 성별 */
	AREA VARCHAR2(50), /* 지역 */
	BIRTH DATE /* 생년월일 */
);

COMMENT ON TABLE VISIT_H IS '방문자';

COMMENT ON COLUMN VISIT_H.ID IS '접속한BLOG_ID';

COMMENT ON COLUMN VISIT_H.V_ID IS '방문자 ID';

COMMENT ON COLUMN VISIT_H.VDATE IS '날짜';

COMMENT ON COLUMN VISIT_H.SEX IS '성별';

COMMENT ON COLUMN VISIT_H.AREA IS '지역';

COMMENT ON COLUMN VISIT_H.BIRTH IS '생년월일';

CREATE UNIQUE INDEX PK_VISIT_H
	ON VISIT_H (
		ID ASC
	);

ALTER TABLE VISIT_H
	ADD
		CONSTRAINT PK_VISIT_H
		PRIMARY KEY (
			ID
		);

/* 검색어저장 */
CREATE TABLE SEARCH_H (
	SEQ NUMBER NOT NULL, /* 시퀀스 */
	SEARCH_WORD VARCHAR2(200) NOT NULL, /* 검색어 */
	S_ID VARCHAR2(50), /* 검색자 ID */
	SDATE DATE DEFAULT SYSDATE NOT NULL, /* 날짜 */
	SEX VARCHAR2(10), /* 성별 */
	AREA VARCHAR2(50), /* 지역 */
	BIRTH DATE /* 생년월일 */
);

COMMENT ON TABLE SEARCH_H IS '검색어저장';

COMMENT ON COLUMN SEARCH_H.SEQ IS '시퀀스';

COMMENT ON COLUMN SEARCH_H.SEARCH_WORD IS '검색어';

COMMENT ON COLUMN SEARCH_H.S_ID IS '검색자 ID';

COMMENT ON COLUMN SEARCH_H.SDATE IS '날짜';

COMMENT ON COLUMN SEARCH_H.SEX IS '성별';

COMMENT ON COLUMN SEARCH_H.AREA IS '지역';

COMMENT ON COLUMN SEARCH_H.BIRTH IS '생년월일';

CREATE UNIQUE INDEX PK_SEARCH_H
	ON SEARCH_H (
		SEQ ASC
	);

ALTER TABLE SEARCH_H
	ADD
		CONSTRAINT PK_SEARCH_H
		PRIMARY KEY (
			SEQ
		);